ALTER TABLE leaders ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE leaders ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;

ALTER TABLE leads ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
